SearchBayesianSkopt: Resuming 'SLIMElasticNetRecommender' Failed, no such file exists.
SearchBayesianSkopt: New best config found. Config 0: {'topK': 710, 'l1_ratio': 0.003314425862029315, 'alpha': 0.6993501648409784} - results: PRECISION: 0.0196537, PRECISION_RECALL_MIN_DEN: 0.0424403, RECALL: 0.0413494, MAP: 0.0078639, MAP_MIN_DEN: 0.0168974, MRR: 0.0640939, NDCG: nan, F1: 0.0266435, HIT_RATE: 0.1610624, ARHR_ALL_HITS: 0.0708447, NOVELTY: 0.0044883, AVERAGE_POPULARITY: 0.1924450, DIVERSITY_MEAN_INTER_LIST: 0.9121721, DIVERSITY_HERFINDAHL: 0.9912149, COVERAGE_ITEM: 0.1040111, COVERAGE_ITEM_HIT: 0.0221569, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.1506162, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0135983, SHANNON_ENTROPY: 8.3635494, RATIO_DIVERSITY_HERFINDAHL: 0.9916775, RATIO_DIVERSITY_GINI: 0.0311895, RATIO_SHANNON_ENTROPY: 0.6346809, RATIO_AVERAGE_POPULARITY: 3.1478481, RATIO_NOVELTY: 0.5162885, 
SearchBayesianSkopt: Config 0 Exception. Config: {'topK': 710, 'l1_ratio': 0.003314425862029315, 'alpha': 0.6993501648409784} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: New best config found. Config 1: {'topK': 104, 'l1_ratio': 0.0035031375065497548, 'alpha': 0.017599974308866652} - results: PRECISION: 0.0119500, PRECISION_RECALL_MIN_DEN: 0.0252871, RECALL: 0.0246009, MAP: 0.0043695, MAP_MIN_DEN: 0.0093154, MRR: 0.0381340, NDCG: nan, F1: 0.0160861, HIT_RATE: 0.1048832, ARHR_ALL_HITS: 0.0407763, NOVELTY: 0.0049645, AVERAGE_POPULARITY: 0.0779457, DIVERSITY_MEAN_INTER_LIST: 0.9770252, DIVERSITY_HERFINDAHL: 0.9977000, COVERAGE_ITEM: 0.1649325, COVERAGE_ITEM_HIT: 0.0306851, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.0980807, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0281988, SHANNON_ENTROPY: 9.7195834, RATIO_DIVERSITY_HERFINDAHL: 0.9981656, RATIO_DIVERSITY_GINI: 0.0646775, RATIO_SHANNON_ENTROPY: 0.7375856, RATIO_AVERAGE_POPULARITY: 1.2749676, RATIO_NOVELTY: 0.5710662, 
SearchBayesianSkopt: Config 1 Exception. Config: {'topK': 104, 'l1_ratio': 0.0035031375065497548, 'alpha': 0.017599974308866652} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: New best config found. Config 2: {'topK': 19, 'l1_ratio': 0.061771132149612384, 'alpha': 0.028687814449902926} - results: PRECISION: 0.0121478, PRECISION_RECALL_MIN_DEN: 0.0253783, RECALL: 0.0246708, MAP: 0.0045212, MAP_MIN_DEN: 0.0094760, MRR: 0.0393615, NDCG: nan, F1: 0.0162796, HIT_RATE: 0.1064245, ARHR_ALL_HITS: 0.0421488, NOVELTY: 0.0052334, AVERAGE_POPULARITY: 0.0536394, DIVERSITY_MEAN_INTER_LIST: 0.9881675, DIVERSITY_HERFINDAHL: 0.9988142, COVERAGE_ITEM: 0.1652589, COVERAGE_ITEM_HIT: 0.0339903, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.0995220, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0440764, SHANNON_ENTROPY: 10.4602103, RATIO_DIVERSITY_HERFINDAHL: 0.9992804, RATIO_DIVERSITY_GINI: 0.1010947, RATIO_SHANNON_ENTROPY: 0.7937892, RATIO_AVERAGE_POPULARITY: 0.8773864, RATIO_NOVELTY: 0.6019920, 
SearchBayesianSkopt: Config 2 Exception. Config: {'topK': 19, 'l1_ratio': 0.061771132149612384, 'alpha': 0.028687814449902926} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: New best config found. Config 3: {'topK': 502, 'l1_ratio': 0.7116052454982603, 'alpha': 0.4074757856186557} - results: PRECISION: 0.0167356, PRECISION_RECALL_MIN_DEN: 0.0350976, RECALL: 0.0341102, MAP: 0.0070748, MAP_MIN_DEN: 0.0150667, MRR: 0.0580690, NDCG: nan, F1: 0.0224543, HIT_RATE: 0.1362994, ARHR_ALL_HITS: 0.0640115, NOVELTY: 0.0051184, AVERAGE_POPULARITY: 0.1507442, DIVERSITY_MEAN_INTER_LIST: 0.8473803, DIVERSITY_HERFINDAHL: 0.9847359, COVERAGE_ITEM: 0.0252173, COVERAGE_ITEM_HIT: 0.0106500, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.1274592, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0040809, SHANNON_ENTROPY: 6.9080482, RATIO_DIVERSITY_HERFINDAHL: 0.9851954, RATIO_DIVERSITY_GINI: 0.0093599, RATIO_SHANNON_ENTROPY: 0.5242279, RATIO_AVERAGE_POPULARITY: 2.4657423, RATIO_NOVELTY: 0.5887676, 
SearchBayesianSkopt: Config 3 Exception. Config: {'topK': 502, 'l1_ratio': 0.7116052454982603, 'alpha': 0.4074757856186557} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: New best config found. Config 4: {'topK': 269, 'l1_ratio': 0.0002581967257909499, 'alpha': 0.015796666980579372} - results: PRECISION: 0.0128619, PRECISION_RECALL_MIN_DEN: 0.0273254, RECALL: 0.0265817, MAP: 0.0047329, MAP_MIN_DEN: 0.0100440, MRR: 0.0407660, NDCG: nan, F1: 0.0173357, HIT_RATE: 0.1116391, ARHR_ALL_HITS: 0.0438689, NOVELTY: 0.0048174, AVERAGE_POPULARITY: 0.0982217, DIVERSITY_MEAN_INTER_LIST: 0.9648349, DIVERSITY_HERFINDAHL: 0.9964810, COVERAGE_ITEM: 0.1371037, COVERAGE_ITEM_HIT: 0.0288489, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.1043984, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0214768, SHANNON_ENTROPY: 9.2522414, RATIO_DIVERSITY_HERFINDAHL: 0.9969461, RATIO_DIVERSITY_GINI: 0.0492597, RATIO_SHANNON_ENTROPY: 0.7021206, RATIO_AVERAGE_POPULARITY: 1.6066251, RATIO_NOVELTY: 0.5541493, 
SearchBayesianSkopt: Config 4 Exception. Config: {'topK': 269, 'l1_ratio': 0.0002581967257909499, 'alpha': 0.015796666980579372} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: Search interrupted due to ValueError. The evaluated configurations may have had all the same value.
